[versions]
agp = "8.5.2"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
material = "1.13.0"
activity = "1.10.1"
constraintlayout = "2.2.1"

agl = "8.5.2"
rxandroid = "3.0.2"
rxjava = "3.1.5"
okhttp = "3.14.9"
okhttptls = "3.14.9"
zxing = "4.3.0"
jsch = "0.1.55"
slf4j = "1.7.36"
gson = "2.10.1"
jaxb = "2.3.1"
backport = "1.0.0"
bouncycastle = "1.70"
circulrprogress = "1.4.0"
commonsnet = "3.9.0"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
rxandroid = { module = "io.reactivex.rxjava3:rxandroid", version.ref = "rxandroid" }
rxjava = { module = "io.reactivex.rxjava3:rxjava", version.ref = "rxjava"}
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp"}
okhttptls = { module = "com.squareup.okhttp3:okhttp-tls", version.ref = "okhttptls"}
zxing = { module = "com.journeyapps:zxing-android-embedded", version.ref = "zxing"}
jsch = { module = "com.jcraft:jsch", version.ref = "jsch"}
slf4j = { module = "org.slf4j:slf4j-api", version.ref = "slf4j"}
gson = { module = "com.google.code.gson:gson", version.ref = "gson"}
jaxb = { group = "javax.xml.bind", name = "jaxb-api", version.ref = "jaxb" }
backport = {group = "com.github.seratch", name = "java-time-backport", version.ref = "backport"}
circulrprogress = { module="com.mikhaellopez:circularfillableloaders", version.ref="circulrprogress"}
bouncycastle = {group = "org.bouncycastle", name = "bcprov-jdk15on", version.ref = "bouncycastle"}
commonsnet = {module="commons-net:commons-net", version.ref="commonsnet"}

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agl"}
